### ISSUE TITLE
Merging with Cake.Handlebars

### ISSUE THREAD

**Issue by gep13** [thzinc/Cake.HandlebarsDotNet#2]
@thzinc I wanted to reach out to start a discussion about merging this project with Cake.Handlebars.

Currently, what are the differences between the two projects?

If we got Cake.Handlebars moved into the Cake-Contrib Organisation, would you be interested in contributing?

@agc93 what are your thoughts?

**Comment by thzinc** [comment]
@gep13, I'd love to merge projects and get this into Cake-Contrib. Honestly, I started this addin after an inadequate search for other Handlebars projects, and only when I tried to push to NuGet with Cake.Handlebars as the ID did I realize that another project existed.

The only feature in this project that is nice is a render-to-file alias. I could easily contribute it to Cake.Handlebars and kill off this project. @agc93's project is quite nicer to use because they did the work of pulling in the Handlebars library so it doesn't have to be loaded manually.

**Comment by gep13** [comment]
@thzinc that is great news.  Okay, so let's quick start this thing with getting @agc93 to transfer the repo to the Cake Contrib Organisation.  @agc93 is that something you are happy to do?  If not, if you transfer it to me, I will get it added into the Org, and get @thzinc set up with permissions, etc.

**Comment by gep13** [comment]
@agc93 did we get this repo moved over to cake-contrib?
